authorName: Nikhil
experimentName: cartpole
trialConcurrency: 2
maxExecDuration: 10h
maxTrialNum: 20
#choice: local, remote, pai
trainingServicePlatform: local
searchSpacePath: ../../modeling/rnn_tf/search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python modeling/rnn_tf/Train_nni.py --num_epochs=5 --rnn_name --inputs_list --outputs_list --close_loop_for --cheat_dt
  codeDir: ../../
  gpuNum: 0