PATH_TO_EXPERIMENT_RECORDINGS_DEFAULT: ./Experiment_Recordings/
controller: neural-imitator-tf
dt:
  control: 0.02
  saving: 0.02
  simulation: 0.002
length_of_experiment: 30
number_of_experiments: 1
random_initial_state:
  angle: 0.785398
  angleD: null
  init_limits:
    angle:
    - 90.0
    - 180.0
    angleD: 40.0
    position: 0.5
    positionD: 0.01
  position: 0
  positionD: null
  target_position: null
save_mode: online
seed: 1998
show_controller_report: false
show_summary_plots: false
split:
- 0.8
- 0.1
start_at_target: true
target_position_end: null
track_fraction_usable_for_target_position: 0.9
turning_points:
  interpolation_type: 0-derivative-smooth
  track_relative_complexity: 1
  turning_points: null
  turning_points_period: regular
