custom-mpc-scipy:
  controller_logging: true
  ftol: 1.0e-08
  l1: 100.0
  l1_2: 0.0
  l2: 0.0
  l3: 0.0
  l4: 0.01
  m1: 0.0
  m2: 0.0
  m3: 0.0
  m4: 0.0
  method: SLSQP
  mpc_horizon: 10
  seed: null
  wr: 0.001
do-mpc:
  angleD_init: 0.0
  angle_init: 0.0
  controller_logging: true
  l_angle: 0.1
  l_position: 1.0
  l_positionD: 0.1
  mpc_horizon: 50
  num_rollouts: 1
  p_Q: 0.0
  p_angle: 0.0
  p_position: 0.0
  p_positionD: 0.0
  positionD_init: 0.0
  position_init: 0.0
  seed: null
do-mpc-discrete:
  angleD_init: 0.0
  angle_init: 0.0
  controller_logging: true
  mpc_horizon: 50
  num_rollouts: 1
  positionD_init: 0.0
  position_init: 0.0
lqr:
  Q:
  - 10.0
  - 1.0
  - 1.0
  - 1.0
  R: 10.0
  control_noise: null
  controller_logging: true
  seed: null
mpc:
  computation_library: tensorflow
  controller_logging: false
  cost_function_specification: quadratic_boundary_grad
  optimizer: mppi
  predictor_specification: K1Incremental-6IN-Dense-32H1-32H2-5OUT-0
mpc-opti:
  controller_logging: true
  mpc_horizon: 10
mppi-cartpole:
  LBD: 100.0
  NU: 1000.0
  R: 1.0
  SAMPLING_TYPE: interpolated
  SQRTRHOINV: 0.02
  WASH_OUT_LEN: 100
  cc_weight: 1.0
  ccrc_weight: 1.0
  control_noise: null
  controller_logging: false
  cost_function_specification: default
  cost_noise: 0.0
  dd_weight: 120.0
  ekc_weight: 5.0
  ekp_weight: 0.01
  ep_weight: 50000.0
  mpc_horizon: 35
  num_rollouts: 3500
  predictor_specification: ODE_TF
  seed: null
  update_every: 1
neural-imitator-pytorch:
  PATH_TO_MODELS: ./Control_Toolkit_ASF/Controllers/models_for_neural_imitator_tf/
  controller_logging: true
  net_name: GRU-6IN-32H1-32H2-1OUT-0
  seed: null
neural-imitator-tf:
  PATH_TO_MODELS: ./Control_Toolkit_ASF/Controllers/models_for_neural_imitator_tf/
  controller_logging: true
  net_name: GRU-6IN-32H1-32H2-1OUT-4
  seed: null
pid:
  D_angle: 0.0
  D_position: 0.1
  I_angle: 0.0
  I_position: 0.0
  P_angle: 9.0
  P_position: 0.1
  controller_logging: true
secloc:
  controller_logging: true
  dead_band: 0.0025
  log_base: 1.05
  pid_Kd: 0.0
  pid_Ki: 1.0
  pid_Kp: 15.0
  ref_period: 1
