
predictors_specifications_testing_Exp_1: ['SGP_10_1_10', 'SGP_10_51_10', 'SGP_10_101_10', 'SGP_10_151_10', 'SGP_10_201_10', 'SGP_10_251_10', 'SGP_10_301_10', 'SGP_10_351_10']

predictors_specifications_testing_Exp_2: ['SGP_2_400_10', 'SGP_7_400_10', 'SGP_12_400_10', 'SGP_17_400_10', 'SGP_22_400_10', 'SGP_27_400_10', 'SGP_32_400_10', 'SGP_37_400_10', 'SGP_42_400_10', 'SGP_47_400_10', 'SGP_52_400_10', 'SGP_57_400_10', 'SGP_62_400_10', 'SGP_67_400_10', 'SGP_72_400_10', 'SGP_77_400_10', 'SGP_82_400_10', 'SGP_87_400_10', 'SGP_92_400_10', 'SGP_97_400_10']

predictors_specifications_testing_Exp_3: []

# predictors_specifications may be a names from the list of predictors in config_predictors.yml (assuming specification make sense)
# It can be a names of networks or GPs e.g. 'GRU-6IN-32H1-32H2-5OUT-0' to be used for test
# For multiple network they must be in the same folder specified in predictors:neural_default:path_to_model
# One can also specify full path to each model as name,
# in this case the path from predictors:neural_default:path_to_model get overwritten
# Where multiple ODE models are available, one can specify the name after colon e.g. ["ODE_TF:simple", "ODE:st"]
# In this case name from predictor_config is getting overwritten

test_file: 'Experiment-2.csv'

path_to_testfile: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Recordings/Test/'

features_to_plot: [ 'angle',      # Only to indicate what odd to be displayed in Brunton Test
                    'angleD',
                    'angle_cos',
                    'angle_sin',
                    'position',
                    'positionD',
        ]
control_inputs: [ 'Q' ]   # Indicates which inputs to network are control_input, TODO: Not sure how it would work with multiple inputs

test_len: 'max'
test_max_horizon: 50  # Indicates prediction horizon for testing
test_start_idx: 0  # Indicates starting point from which data from test file should be taken

decimation: 1  # If your dataset has sampling frequency being multiple of your network's sampling frequency
