board: 'digilentinc.com:zybo-z7-20:part0:1.0'
part: 'XC7Z020'
path_to_hls_installation: '/tools/Xilinx/Vivado/2020.1/bin'


path_to_models: './IROS24_CPP_v2/'
net_name: 'Dense-7IN-32H1-32H2-1OUT-8'
batch_size: 1


PRECISION:
  input_and_output: 'fixed<12,2>'
  activations: 'fixed<12,1>'
  weights_and_biases: 'fixed<12,4>'
  intermediate_results: 'fixed<18,6>'  # Also set as "Model precision" and used for all quantizations not included above

Strategy: 'Resources'  # Resources or Latency
ReuseFactor: 32

backend: 'Vivado'  # VivadoAccelerator or Vivado
#backend: 'VivadoAccelerator'  # VivadoAccelerator or Vivado

with_brunton_testing: false

output_dir: '../../CPP_IROS/x3232_12_2_v1' # Must be a very short path neer to the root filesystem. Otherwise it crashes silently