testing:
  tests: ['EulerNoisy', 'Hybrid Dense-6IN-16H1-16H2-5OUT-0', 'Hybrid Dense-6IN-32H1-32H2-5OUT-0',  'Hybrid GRU-6IN-32H1-32H2-5OUT-2', 'Hybrid GRU-6IN-32H1-32H2-5OUT-1']  # May be 'Euler', Euler-predictor, 'Hybrid, 'Hybrid_diff', name of network or None = 'Dense-16H1-16H2'
  TEST_FILE: 'Experiment-1.csv'
  features: ['angle',
     'angleD',
     'angle_cos',
     'angle_sin',
     'position',
     'positionD',
     ]
  control_inputs: ['Q']   # Indicates which inputs to network are control_input, TODO: Not sure how it would work with multiple inputs
  PATH_TO_NN: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Models/'  # Path where the neural network models are stored './SI_Toolkit_ASF/Experiments/Physical-Experiment-Augmented-diff/Models/'
  PATH_TO_TEST_FILE: './SI_Toolkit_ASF/Experiments/Physical-Experiment-Augmented/Recordings/Test/'
  TEST_LEN: 'max'
  MAX_HORIZON: 50  # Indicates prediction horizon for testing
  START_IDX: 0  # Indicates from which point data from test file should be taken
  DECIMATION: 1  # Only useful if the testing file has data saved at higher frequency rate than required by NN