predictor_name_default: '2_layer_gru'
# If controller does not specify predictor_specification (leave empty)
# a predictor from "predictors:predictor_name_default" from below is loaded
# Check config.yml and config_testing.yml to learn more on how predictors are selected

predictors:
  ### THESE ARE DEFAULT PREDICTORS! DON'T CHANGE THEM, RATHER ADD YOUR PREDICTOR BELOW
  neural_default:
    predictor_type: 'neural'
    model_name: 'GRU-6IN-32H1-32H2-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Experiment-2/Models/'
    update_before_predicting: True
  GP_default:
    predictor_type: 'GP'
    model_name: 'SGP_10'
    path_to_model: './SI_Toolkit_ASF/Experiments/Experiment-2/Models/'
  ODE_default:
    predictor_type: 'ODE'
    model_name:
    intermediate_steps: 10
  ODE_TF_default:
    predictor_type: 'ODE_TF'
    model_name:
    intermediate_steps: 10

  # ADD YOUR PREDICTORS BELOW

  2_layer_gru:
    predictor_type: 'neural'  # Possible options are: 'neural', 'GP', 'ODE, 'ODE_TF'
    model_name: 'GRU-6IN-32H1-32H2-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Experiment-16/Models/'
    update_before_predicting: True
  
  3_layer_gru:
    predictor_type: 'neural'  # Possible options are: 'neural', 'GP', 'ODE, 'ODE_TF'
    model_name: 'GRU-6IN-16H1-16H2-16H3-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Experiment-15/Models/'
    update_before_predicting: True
  
  1_layer_gru_64:
    predictor_type: 'neural'  # Possible options are: 'neural', 'GP', 'ODE, 'ODE_TF'
    model_name: 'GRU-6IN-64H1-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Experiment-16/Models/'
    update_before_predicting: True

  ODE_TF:
    predictor_type: 'ODE_TF'
    model_name:
    intermediate_steps: 10
