predictor_name_main: 'I_love_control'


testing:
  predictor_names_testing: ['I_love_control', 'I_love_control_too', 'GRU-6IN-32H1-32H2-5OUT-0']

  # 'predictor_names_testing' may be a names from the list of predictors below (assuming specification make sense)
  # It can be a names of networks e.g. 'GRU-6IN-32H1-32H2-5OUT-0' to be used for test
  # For multiple network they must be in the same folder specified in predictors:neural:path_to_model
  # One can also specify full path to each model as name,
  # but in this case the predictors:neural:path_to_model must be empty
  # Also otherwise the specifications from
  # Where multiple ODE models are available, one can specify the name after colon e.g. ["ODE_TF:simple", "ODE:st"]
  # In this case name from predictor_config is getting overwritten

  TEST_FILE: 'Experiment-1.csv'

  PATH_TO_TEST_FILE: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Recordings/Test/'

  FEATURES_TO_PLOT: [ 'angle',      # Only to indicate what odd to be displayed in Brunton Test
                      'angleD',
                      'angle_cos',
                      'angle_sin',
                      'position',
                      'positionD',
          ]
  CONTROL_INPUTS: [ 'Q' ]   # Indicates which inputs to network are control_input, TODO: Not sure how it would work with multiple inputs

  TEST_LEN: 'max'
  MAX_HORIZON: 50  # Indicates prediction horizon for testing
  START_IDX: 0  # Indicates starting point from which data from test file should be taken

  DECIMATION: 1  # If your dataset has sampling frequency being multiple of your network's sampling frequency


predictors:
  ### THESE ARE DEFAULT PREDICTORS! DON'T CHANGE THEM, RATHER ADD YOUR PREDICTOR BELOW
  neural:
    predictor_type: 'neural'
    model_name: 'GRU-6IN-32H1-32H2-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Models/'
    dt: # Matters only for differential network
    update_before_predicting: True
  GP:
    predictor_type: 'GP'
    model_name:
    path_to_model:
  ODE:
    predictor_type: 'ODE'
    model_name:
    dt: 0.02
    intermediate_steps: 10
  ODE_TF:
    predictor_type: 'ODE_TF'
    model_name:
    dt: 0.02
    intermediate_steps: 10

  # ADD YOUR PREDICTORS BELOW

  I_love_control:
    predictor_type: 'neural'  # Possible options are: 'neural', 'GP', 'ODE, 'ODE_TF'
    model_name: 'GRU-6IN-32H1-32H2-5OUT-0'
    path_to_model: './SI_Toolkit_ASF/Experiments/Pretrained-RNN-1/Models/'
    dt: # Matters only for differential network
    update_before_predicting: True

  I_love_control_too:
    predictor_type: 'ODE'
    model_name:
    dt: 0.02
    intermediate_steps: 10
